openapi: 3.0.0
info:
  version: 1.0.0
  title: Магазин игрушек OpenAPI спецификация.
  license:
    name: MIT
  description:  Toys Shop API

host: "petstore.swagger.io"
basePath: "/v2"
servers: 
  - url: http://localhost:8080/api/v1/
    description:  Dev server
paths:
  /toys:
    get:
      summary: Метод получения списка игрушек
      tags:
        - Toys
      operationId: getAllToys
      responses: 
        '200': 
          descriptions: Успешный ответ со списком игрушек
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Toys"
        'default': 
          descriptions: Всё не стандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /toys/{toy_id}:
    get:
      summary: Метод получения игрушеки по идентификатору
      tags:
        - Toys
      operationId: getToyById
      parametrs:
        - name: toy_id
        in: path
        required: true
        description: Идентификатор игрушки
        schema:
          type: string
      responses: 
        '200': 
          descriptions: Успешный ответ со списком игрушек
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Toys"
        'default': 
          description: Всё не стандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  


              
components:
  schemas:
    Toy:
      type: object
      required:
        - name
        - status
      properties:
        toy_id:
          type: string
          example: 12344234
        name:
          type: string
          example: Train
        status:
          type: string
          enum:
            - new
            - old
            - broken
          description: Состояние игрушки
        created_at:
          type: string
          format: 2022-07-01T15:00:00+01
    Toys:
      type: array
      items:
        $ref: "#/components/schemas/Toy"
    Error:
      type: object
      required:
         - code
         - message
      properties:
        code:
          type: integer
        message:
          type: string
    
    
